name: Bump stale issues

on:
  schedule:
  - cron: '41 1 * * */2'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/fresh-bot.yml'
  workflow_dispatch: { }

jobs:
  rate-limits:
    name: Check rate limits
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: fresh-bot
      cancel-in-progress: true
    steps:
    - name: Get rate limits
      uses: remal-github-actions/get-rate-limits@v1
      id: getRateLimits
      with:
        githubToken: ${{env.PERSONAL_ACCESS_TOKEN || github.token}}
    - name: Make decision
      id: decision
      run: |
        echo "Core rate limit usage: ${{steps.getRateLimits.outputs.coreUsage}}"
        if [ "${{steps.getRateLimits.outputs.coreUsage < 25}}" == "true" ]; then
          echo "Enough rate limits"
          echo 'enough=true' >> $GITHUB_OUTPUT
        else
          echo "::warning::Not enough rate limits!"
          if [ "${{github.event_name != 'schedule'}}" == "true" ]; then
            echo "::warning::Executing anyway, as event is '${{github.event_name}}'"
          fi
          echo 'enough=false' >> $GITHUB_OUTPUT
        fi
    outputs:
      enough: ${{steps.decision.outputs.enough}}

  fresh-bot:
    needs:
    - rate-limits
    if: ${{github.event_name != 'schedule' || fromJSON(needs.rate-limits.outputs.enough) == true}}
    name: Bump stale issues
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: fresh-bot
      cancel-in-progress: true
    steps:
    - name: Bump stale issues
      uses: c-hive/fresh-bot@v1
      with:
        GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
