name: Manage dependency updates notifications

on:
  schedule:
  - cron: '0/15 * * * *'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/manage-dependency-updates-notifications.yml'
  workflow_dispatch: { }

jobs:
  manage-dependency-updates-notifications:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Manage dependency updates notifications
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.NOTIFICATIONS_TOKEN }}
        script: |
          const notifications = await github.paginate(
            github.rest.activity.listNotificationsForAuthenticatedUser.endpoint.merge({})
          )
          for (const notification of notifications) {
            if (notification.subject == null || notification.subject.type !== 'PullRequest') continue;
            if (notification.repository == null) continue;
            
            if (notification.reason !== 'assign') {
              console.log(JSON.stringify(notification, null, 2))
              continue;
            }

            const repositoryUrl = notification.repository.url
            let pullRequestId = notification.subject.url
            if (pullRequestId.startsWith(repositoryUrl)) {
              pullRequestId = pullRequestId.substring(repositoryUrl.length)
            }
            if (pullRequestId.startsWith('/pulls/')) {
              pullRequestId = pullRequestId.substring('/pulls/'.length)
            }
            
            const pullRequest = await github.rest.pulls.get({
              owner: notification.repository.owner.login,
              repo: notification.repository.name,
              pull_number: pullRequestId,
            }).then(it => it.data)
            console.log(JSON.stringify(pullRequest, null, 2))
            
            if (pullRequest.user.login === 'renovate[bot]'
              || pullRequest.user.login === 'dependabot[bot]'
            ) {
            
              let canNotificationBeDeleted = pullRequest.merged
            
              if (!canNotificationBeDeleted) {
                let statusesRef = pullRequest.statuses_url
                if (statusesRef.startsWith(repositoryUrl)) {
                  statusesRef = statusesRef.substring(repositoryUrl.length)
                }
                if (statusesRef.startsWith('/statuses/')) {
                  statusesRef = statusesRef.substring('/statuses/'.length)
                }
                const statuses = await github.paginate(
                  github.rest.repos.listCommitStatusesForRef.endpoint.merge({
                    owner: notification.repository.owner.login,
                    repo: notification.repository.name,
                    ref: statusesRef,
                  })
                )
                console.log(JSON.stringify(statuses, null, 2))
              }
              
              if (canNotificationBeDeleted) {
                console.log("Marking thread as read: '" + notification.subject.title + "' (" + notification.id + ")")
                await github.rest.activity.markThreadAsRead({
                  thread_id: notification.id,
                })
              }
              
            }
          }
