name: Execute sync-with-template.yml for all repos

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/sync-with-template.yml'
  workflow_dispatch: { }

jobs:
  sync-with-template:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Manage dependency updates notifications
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}    
        script: |
          const repos = await github.paginate(github.rest.repos.listForAuthenticatedUser)
          for (const repo of repos) {
            console.log(repo.full_name)
          }
