name: Execute sync-with-template.yml for all repos

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/sync-with-template.yml'
  workflow_dispatch: { }

jobs:
  sync-with-template:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Execute sync-with-template.yml for all repos
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}    
        script: |
          const repos = await github.paginate(github.rest.repos.listForAuthenticatedUser, {
            visibility: 'public',
          })
          for (const repo of repos) {
            if (repo.fork) continue
            if (repo.archived) continue
            if (!repo.permissions.push) continue
            await core.group("Processing " + repo.full_name, async () => {
              const workflowFile = '.github/workflows/sync-with-template.yml'
              const workflowExists = await github.rest.repos.getContent({
                owner: repo.owner.login,
                repo: repo.name,
                path: workflowFile,
              }).then(
                () => true,
                error => { if (error.response && error.response.status === 404) return false; else throw error; }
              )
              
              const workflow = workflowFile.replace(/^.*\/([^/]+)$/, '$1')
              core.info('Creating a workflow dispatch event for ' + workflow)
              await github.rest.actions.createWorkflowDispatch({
                owner: repo.owner.login,
                repo: repo.name,
                workflow_id: workflow,
                ref: repo.default_branch,
              })
            })
          }
