name: Execute sync-with-template.yml for all repos

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/sync-with-template.yml'
  workflow_dispatch: { }

jobs:
  sync-with-template:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - name: Execute sync-with-template.yml for all repos
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}    
        script: |
          const repos = await github.paginate(github.rest.repos.listForAuthenticatedUser, {
            visibility: 'public',
          })
          for (const repo of repos) {
            const workflowExists = await github.rest.repos.getContent({
              owner: repo.owner.login,
              repo: repo.name,
              path: 'asd/.github/workflows/sync-with-template.yml',
            }).then(
              () => true,
              error => { if (error.response && error.response.status === 404) return false else throw error }
            )
            core.info('workflowExists: ' + workflowExists)
          }
